### ISSUE TITLE
When sending a mail fails, allow user to try again

### ISSUE THREAD

**Issue by dudadornelles** [pixelated-project/pixelated-user-agent#295] opened 2015-02-18 12:33 UTC
Right now, when sending a mail fails, the 'Send' button changes to 'Sending' and gets stuck.

![screen shot 2015-02-18 at 10 36 32 am](https://cloud.githubusercontent.com/assets/249770/6247284/d43ec12a-b759-11e4-8b8a-115838db039a.png)

It would be better if it would get enabled again and the text changed to 'Send'.

**Comment by tiagoferraz** [comment] 2015-02-19 20:10
If the sending button is stuck on Sending... because the user entered a wrong email address, if the user deletes and add one valid, the button will get to the darker blue , be clickable and the user can send the email again.
![screen shot 2015-02-19 at 6 07 41 pm](https://cloud.githubusercontent.com/assets/2946807/6274965/8ba15f18-b862-11e4-96ff-05efa448d44e.png)

**Comment by fbernitt** [comment] 2015-03-20 16:15
Seems to be a duplicate of #189. We should decide on a consistent user feedback when it comes to this button.

**Closed by fbernitt** 2015-03-20 16:15 UTC
Labels: 1 - Ready, Beginners, bug
