### ISSUE TITLE
vagrant source box: conflict in the installed version  of gnupg

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#392] opened 2015-05-11 09:25 UTC
even with the recommended steps, i can't fix the error:

```
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pixelated-user-agent --config /vagrant/config/try.pixelated-project.org.config 
*******
Ooops! It looks like there is a conflict in the installed version 
of gnupg.

Disclaimer: Ideally, we would need to work a patch and propose the 
merge to upstream. But until then do: 

% pip uninstall python-gnupg
% pip install gnupg
*******
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pip uninstall python-gnupg
Cannot uninstall requirement python-gnupg, not installed
Storing complete log in /home/vagrant/.pip/pip.log
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pip install gnupg
Requirement already satisfied (use --upgrade to upgrade): gnupg in /home/vagrant/user-agent-venv/lib/python2.7/site-packages
Cleaning up...
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pixelated-user-agent --config /vagrant/config/try.pixelated-project.org.config 
*******
Ooops! It looks like there is a conflict in the installed version 
of gnupg.

Disclaimer: Ideally, we would need to work a patch and propose the 
merge to upstream. But until then do: 

% pip uninstall python-gnupg
% pip install gnupg
*******
```

for the record, here's the complete log from when i started the box.

```
--- git/pixelated-user-agent ‹master› » vagrant up
Bringing machine 'source' up with 'libvirt' provider...
==> source: Creating image (snapshot of base box volume).
==> source: Creating domain with the following settings...
==> source:  -- Name:              pixelated-user-agent_source
==> source:  -- Domain type:       kvm
==> source:  -- Cpus:              1
==> source:  -- Memory:            1024M
==> source:  -- Base box:          LEAP/wheezy
==> source:  -- Storage pool:      default
==> source:  -- Image:             /home/varac/vagrant/storagepool/pixelated-user-agent_source.img
==> source:  -- Volume Cache:      default
==> source:  -- Kernel:            
==> source:  -- Initrd:            
==> source:  -- Graphics Type:     vnc
==> source:  -- Graphics Port:     5900
==> source:  -- Graphics IP:       127.0.0.1
==> source:  -- Graphics Password: Not defined
==> source:  -- Video Type:        cirrus
==> source:  -- Video VRAM:        9216
==> source:  -- Keymap:            en-us
==> source:  -- Command line : 
==> source: Pruning invalid NFS exports. Administrator privileges will be required...
==> source: Starting domain.
==> source: Waiting for domain to get an IP address...
==> source: Waiting for SSH to become available...
    source: 
    source: Vagrant insecure key detected. Vagrant will automatically replace
    source: this with a newly generated keypair for better security.
    source: 
    source: Inserting generated public key within guest...
    source: Removing insecure key from the guest if its present...
    source: Key inserted! Disconnecting and reconnecting using new SSH key...
==> source: Starting domain.
==> source: Waiting for domain to get an IP address...
==> source: Waiting for SSH to become available...
==> source: Creating shared folders metadata...
==> source: Forwarding ports...
==> source: 3333 => 3333 (adapter eth0)
==> source: Exporting NFS shared folders...
==> source: Preparing to edit /etc/exports. Administrator privileges will be required...
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2015-05-07 19:02:27 CEST; 3 days ago
  Process: 1056 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 1050 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 1056 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/nfs-server.service

May 07 19:02:27 rocinante systemd[1]: Starting NFS server and services...
May 07 19:02:27 rocinante systemd[1]: Started NFS server and services.
==> source: Mounting NFS shared folders...
==> source: Configuring and enabling network interfaces...
==> source: Running provisioner: puppet...
==> source: Running Puppet with source.pp...
==> source: stdin: is not a tty
==> source: notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x287A1542472DC0E3_packages@pixelated-project.org.asc]/ensure: defined content as '{md5}3f582be03f19efaed603b70e9da67a27'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[add_pixelated_key]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/preferences.d/pixelated]/ensure: defined content as '{md5}316b7bd2fd04ad7f565d4e7ad3bd6a43'
==> source: notice: /Stage[main]/Phantomjs/Exec[download_phantomjs]/returns: executed successfully
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/wheezy-backports.list]/ensure: defined content as '{md5}b30d79e4302dbfa2d7cf88299647b264'
==> source: notice: /Stage[main]/Phantomjs/Exec[unpack_phantomjs]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Phantomjs/Exec[install_phantomjs]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Pixelated::Apt/File[/tmp/0x1E34A1828E20790_leap_archive_key]/ensure: defined content as '{md5}c11c9804d356e86b7669a2a89181b32b'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[add_leap_key]: Triggered 'refresh' from 1 events
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/leap.list]/ensure: defined content as '{md5}760e91ebd9de5a10d78fb9977885cb1b'
==> source: notice: /Stage[main]/Pixelated::Apt/File[/etc/apt/sources.list.d/pixelated.list]/ensure: defined content as '{md5}8cb29b17201f94e1189805b7c6bbdbe6'
==> source: notice: /Stage[main]/Pixelated::Apt/Exec[apt_get_update]: Triggered 'refresh' from 6 events
==> source: notice: /Stage[main]/Pixelated::Apt/Package[leap-keyring]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Common/Package[haveged]/ensure: ensure changed 'purged' to 'present'
==> source: notice: /Stage[main]/Pixelated::Source/Package[libfontconfig1]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[git]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[ruby-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[libsqlite3-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[python-virtualenv]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[nodejs-legacy]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[python-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source/Package[libffi-dev]/ensure: ensure changed 'purged' to 'latest'
==> source: notice: /Stage[main]/Pixelated::Source::Npm/Exec[install_npm]/returns: executed successfully
==> source: notice: /Stage[main]/Pixelated::Source/Package[compass]/ensure: created
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/File[/home/vagrant/.activate_custom_node_modules.sh]/ensure: defined content as '{md5}0b46c14a9e524d325bd73a82be025210'


==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[install-pixelated]/returns: executed successfully
==> source: notice: /Stage[install_pixelated]/Pixelated::Source::Install_useragent/Exec[add_custom_node_modules_to_bashrc]/returns: executed successfully
==> source: notice: Finished catalog run in 398.74 seconds
--- git/pixelated-user-agent ‹master› » 
--- git/pixelated-user-agent ‹master› » 
--- git/pixelated-user-agent ‹master› » vagrant ssh source
Linux leap-wheezy 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu Apr 23 17:46:44 2015 from 192.168.122.1
running python setup
warning: no files found matching '*' under directory 'debian'
zip_safe flag not set; analyzing archive contents...
simplejson.tests.__init__: module references __file__
error: Download error for https://pypi.python.org/packages/2.7/p/pysqlcipher/pysqlcipher-2.6.4.1-py2.7-linux-x86_64.egg#md5=d76c8ebd265108800edc53036be0abc3: [Errno 110] Connection timed out
running js setup
npm WARN package.json karma-coverage@0.2.7 No README data
npm WARN package.json karma-firefox-launcher@0.1.4 No README data
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ logout
Connection to 192.168.121.29 closed.
--- git/pixelated-user-agent ‹master› » vagrant ssh source
Linux leap-wheezy 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon May 11 08:25:30 2015 from 192.168.121.1
running python setup
warning: no files found matching '*' under directory 'debian'
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '*.hgignore' found anywhere in distribution
warning: no previously-included files matching '*.hgtags' found anywhere in distribution
warning: no previously-included files matching '*' found under directory 'docs/_build/_sources'
warning: no files found matching '*.html' under directory 'docs/_build'
warning: no files found matching 'OpenSSL/RATIONALE'
warning: no previously-included files found matching 'leakcheck'
warning: no previously-included files matching '*.py' found under directory 'leakcheck'
warning: no previously-included files matching '*.pem' found under directory 'leakcheck'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
no previously-included directories found matching 'doc/_build'
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
jsonschema.tests.test_jsonschema_test_suite: module references __file__
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
warning: no previously-included files matching 'lextab.*' found under directory 'tests'
warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
warning: no previously-included files matching 'lextab.*' found under directory 'examples'
zip_safe flag not set; analyzing archive contents...
running js setup
npm WARN package.json karma-coverage@0.2.7 No README data
npm WARN package.json karma-firefox-launcher@0.1.4 No README data


```

(re-)installing pysqlcipher didn't fix it neither:

```
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pip uninstall -y pysqlcipher 
Uninstalling pysqlcipher:
  Successfully uninstalled pysqlcipher
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pip install pysqlcipher 
Downloading/unpacking pysqlcipher
  Downloading pysqlcipher-2.6.4.tar.gz (71Kb): 71Kb downloaded
  Running setup.py egg_info for package pysqlcipher
    
    warning: no files found matching 'doc/*.txt'
    warning: no files found matching 'doc/includes/sqlite3/*.py'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Installing collected packages: pysqlcipher
  Running setup.py install for pysqlcipher
    Downloading amalgation.
    amalgamation url: https://downloads.leap.se/libs/pysqlcipher/amalgamation-sqlcipher-2.1.0.zip
    Extracting sqlite3.c
    Extracting sqlite3.h
    building 'pysqlcipher._sqlite' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/module.c -o build/temp.linux-x86_64-2.7/src/module.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/connection.c -o build/temp.linux-x86_64-2.7/src/connection.o
    src/connection.c: In function ‘_pysqlite_final_callback’:
    src/connection.c:787:15: warning: variable ‘aggregate_class’ set but not used [-Wunused-but-set-variable]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/cursor.c -o build/temp.linux-x86_64-2.7/src/cursor.o
    src/cursor.c: In function ‘pysqlite_cursor_dealloc’:
    src/cursor.c:129:9: warning: variable ‘rc’ set but not used [-Wunused-but-set-variable]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/cache.c -o build/temp.linux-x86_64-2.7/src/cache.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/microprotocols.c -o build/temp.linux-x86_64-2.7/src/microprotocols.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/prepare_protocol.c -o build/temp.linux-x86_64-2.7/src/prepare_protocol.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/statement.c -o build/temp.linux-x86_64-2.7/src/statement.o
    src/statement.c: In function ‘pysqlite_statement_dealloc’:
    src/statement.c:408:9: warning: variable ‘rc’ set but not used [-Wunused-but-set-variable]
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/util.c -o build/temp.linux-x86_64-2.7/src/util.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c src/row.c -o build/temp.linux-x86_64-2.7/src/row.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMODULE_NAME="pysqlcipher.dbapi2" -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_LOAD_EXTENSION=1 -DSQLITE_HAS_CODEC=1 -DSQLITE_TEMP_STORE=2 -Iamalgamation -I/usr/include/python2.7 -c amalgamation/sqlite3.c -o build/temp.linux-x86_64-2.7/amalgamation/sqlite3.o
    amalgamation/sqlite3.c:13171:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c:13172:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c:13207:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c:13210:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c:13228:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c:13720:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c:13742:6: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c:14048:5: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c:14056:15: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
    amalgamation/sqlite3.c: In function ‘porter_stemmer’:
    amalgamation/sqlite3.c:125273:41: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125277:39: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125290:35: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125295:39: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125301:41: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125306:39: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125315:38: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125322:37: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125365:39: warning: value computed is not used [-Wunused-value]
    amalgamation/sqlite3.c:125385:34: warning: value computed is not used [-Wunused-value]
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-x86_64-2.7/src/module.o build/temp.linux-x86_64-2.7/src/connection.o build/temp.linux-x86_64-2.7/src/cursor.o build/temp.linux-x86_64-2.7/src/cache.o build/temp.linux-x86_64-2.7/src/microprotocols.o build/temp.linux-x86_64-2.7/src/prepare_protocol.o build/temp.linux-x86_64-2.7/src/statement.o build/temp.linux-x86_64-2.7/src/util.o build/temp.linux-x86_64-2.7/src/row.o build/temp.linux-x86_64-2.7/amalgamation/sqlite3.o -o build/lib.linux-x86_64-2.7/pysqlcipher/_sqlite.so -lcrypto
    
    warning: no files found matching 'doc/*.txt'
    warning: no files found matching 'doc/includes/sqlite3/*.py'
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Successfully installed pysqlcipher
Cleaning up...
(user-agent-venv)vagrant@leap-wheezy:/vagrant$ pixelated-user-agent --config /vagrant/config/try.pixelated-project.org.config 
*******
Ooops! It looks like there is a conflict in the installed version 
of gnupg.

Disclaimer: Ideally, we would need to work a patch and propose the 
merge to upstream. But until then do: 

% pip uninstall python-gnupg
% pip install gnupg
*******

```

**Comment by bwgpro** [comment] 2015-05-15 17:58
Hey @varac, you have to reinstall gnupg like this:

```
pip uninstall gnupg
pip install gnupg
```

The problem is that gnupg installed by easy_install is broken, so we have to uninstall it and reinstall by pip.

the ./go setup does the right thing already

**Comment by bwagnerr** [comment] 2015-07-24 20:33
Using ./go setup works and the vagrant setup uses that now, so I'm closing this

**Closed by bwagnerr** 2015-07-24 20:33 UTC
Labels: bug
