### ISSUE TITLE
soldedad fails if one mails can not be decrypted

### ISSUE THREAD

**Issue by cz8s** [pixelated-project/pixelated-user-agent#190] opened 2014-12-15 12:31 UTC
```
2014-12-15 12:29:08+0000 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 839, in _cbDeferred
	    self.callback(self.resultList)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 382, in callback
	    self._startRunCallbacks(result)
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/lib/python2.7/dist-packages/leap/mail/imap/fetch.py", line 600, in _add_message_locally
	    doc, data = msgtuple
	exceptions.TypeError: 'NoneType' object is not iterable

```

**Comment by dudadornelles** [comment] 2015-01-27 15:04
I'll close this since there are no clear steps to reproduce.

**Closed by dudadornelles** 2015-01-27 15:04 UTC
Labels: 0 - Backlog
