### ISSUE TITLE
Vagrant with the debian package still have the u1db_config error

### ISSUE THREAD

**Issue by varac** [pixelated-project/pixelated-user-agent#270] opened 2015-02-04 15:14 UTC
problem: #258 (u1db_config error on subsequent starts of debian package) was QA'ed, but the Vagrant deb box still doesn't work.

We should find a way to ensure that fixes in the useragent are reflected in the vagrant boxes as well. 

One possible task could be that we QA the vagrant boxes once a week, i.e.

**Comment by lqust** [comment] 2015-02-04 16:43
Isn't this a duplicate of https://github.com/pixelated-project/project-issues/issues/82?

**Comment by bwgpro** [comment] 2015-02-05 22:06
This issue is not really actionable. We fixed the problem we had this time (The u1db error on the deb vagrant).

The real issue to make sure this won't happen again without any warning is issue pixelated-project/project-issues#82

**Closed** 2015-02-09 13:02 UTC
Labels: 4 - Done
