### ISSUE TITLE
Not all tags are listed

### ISSUE THREAD

**Issue by tiagoferraz** [pixelated-project/pixelated-user-agent#275] opened 2015-02-05 16:55 UTC
After creating several tags, we verified that not all tags are displayed in the tags pane. It seems to affect on tags formed by letters in it.

**Comment by shyba** [comment] 2015-02-09 19:05
@tiagoferraz Can you provide a screenshot or an example of a tag set that will behave like this?

**Comment by bwgpro** [comment] 2015-04-01 19:04
We could not reproduce this for some time, so we're closing it

**Closed by bwgpro** 2015-04-01 19:04 UTC
Labels: bug
